### ISSUE TITLE
TarGz Build für OSX enthält fehlerhaften Inhalt

### ISSUE THREAD

**Issue by DeathsGun** [kumpelblase2/proxtop#104]
Wenn ich die neue Version öffne stürzt es sofort ab.
[Report](http://hastebin.com/raw/wasoqecako)

**Comment by kumpelblase2** [comment]
Ich hab eben nochmal getestet, der Build in der ZIP läuft einwandfei, der aus der TAR.GZ stürzt ab. Also einfach die ZIP runterladen und die benutzen. Ich werd mal schauen, warum da nen andere Build herauskommt.

**Comment by DeathsGun** [comment]
Ok werde ich gleich mal testen

**Comment by DeathsGun** [comment]
Funktioniert
