### ISSUE TITLE
Add a warning when selecting "Save password" as it has to store the password in plain text.

### ISSUE THREAD

**Issue by kumpelblase2** [kumpelblase2/proxtop#20]

**Comment by mccxiv** [comment]
Is there a better solution to this? How do other programs do it?

**Comment by kumpelblase2** [comment]
So the current situation is this:

Since I have to use the normal login via html form, I also have to enter the password there in plain text. The session times out after about 3 months so it's not really too bad if you don't save it and just reenter it after that time.

The only other way to have the password saved is to encrypt it... But then I would need some other key which either the user would have to enter (thus defeat the purpose) or save it on the hard drive (so an attacker could find it and decrypt it again, this making this equally useless). Sooo yeah....

**Comment by kumpelblase2** [comment]
To clarify how the password is currently used: When the user selects "Save password" the password gets saved in plain text to the config. Once the application notices that the user is no longer logged in and the current action requires the user to be logged in, it will check if the user has saved the password. If that is the case, it will directly login the user again in the background without the user noticing a thing (apart from maybe a bit longer load time). If the user did not save the password, the login page in the app would appear and the user had to login manually.

Again, this only every happens every 3+ months, so I don't see myself putting a lot of effort into finding a better solution to storing the password in plain text. I want to keep it as an option (because people are lazy, myself included), just making sure that people are aware of the implications.
