### ISSUE TITLE
Updating system

### ISSUE THREAD

**Issue by kumpelblase2** [kumpelblase2/proxtop#24]
This has to be done in someway in the long run.

**Comment by kumpelblase2** [comment]
Considering of just cancelling this. Setting up an update server is already a pain in the ass but then also having to deal with NuGet packaging is just horrendous.

**Comment by kumpelblase2** [comment]
I'll keep an eye out on https://github.com/loopline-systems/electron-builder once that gets linux & squirrel supprt.

**Comment by Kazero1** [comment]
Schade eigentlich, vielleicht würde es eine Update Benachrichtigung auch tun?

**Comment by kumpelblase2** [comment]
Hm.. das sollte machbar sein.

**Comment by kumpelblase2** [comment]
Something else to look for: https://github.com/develar/electron-complete-builder

**Comment by Kazero1** [comment]
Rein theoretisch könnte man es darüber auch lösen. Wobei wahrscheinlich die Updatebenachrichtigung wesentlich einfacher ist zum programmieren. Von der Us. her ist es als nutzer mit einem Auto Update wesentlich bequemer xD

**Comment by kumpelblase2** [comment]
Eine einfache Benachrichtigung ist kein Problem. Ich bin auch noch am überlegen, ob es für die meisten updates nicht ausreichen würde das code package (app.asar) auszutauschen (bzw. ob das überhaupt möglich ist), was das auto-update auch um einiges vereinfachen würde. Auf Linux ist auto-update wohl eher keine gute Idee (wegen packages), von daher würde für den ersten Schritt eine Benachrichtigung reichen. Ggf. später dann auf allen System eine Nachricht, die bei Bestätigung das Update durchführt oder eben bei Linux dann auf das GitHub-Release für die Packages weiterleitet.

Aber wie gesagt, erstmal werde ich mir eine Benachrichtigung vornehmen, da ich dann erstmal nichts am Build-Prozess verändern muss.

**Comment by Kazero1** [comment]
Jap das ist eine gute Idee :)

**Comment by kumpelblase2** [comment]
Should do for now https://github.com/kumpelblase2/proxtop/pull/43

**Comment by kumpelblase2** [comment]
I'm planning this for the next release, it's about time.

**Comment by kumpelblase2** [comment]
Since release 0.4.2 the logic is already there, I just disabled it for that release to make sure the process is working as intended (because the old versioning scheme did not work well with it).

Auto updating can be disabled in the settings and (currently) only works on windows 64bit. Linux will continue to be done with update notifications + packages. OSX I will see when I get around getting a signing key, so probably not gonna get auto updates any time soon.

How does it work?
- A small popup will be shown (similar to how it's been working right now) saying that the update is ready. Simple restart the app and it will be installed.
- This requires installing proxtop via the (then) provided installer. 

I will try to still upload a version that uses the old updating style for people who don't like auto updates, while still would like to receive news about new updates. Otherwise there will be an 32bit version available in this case.

**Comment by kumpelblase2** [comment]
Tested and should work in the 1.0 release, currently will only work with the installer on windows.
