### ISSUE TITLE
Runtime exception at startup

### ISSUE THREAD

**Issue by rubengees** [kumpelblase2/proxtop#48]
### Version used
0.2
### OS
Windows 10 Pro
### Steps to reproduce
Start the application :D
### Stacktrace  
I can't copy it from the window so screenshots only

![Exception 1](https://cloud.githubusercontent.com/assets/8021265/13203769/203464ea-d8bf-11e5-82e5-924bbb945029.png)
![Exception 2](https://cloud.githubusercontent.com/assets/8021265/13203770/237006fa-d8bf-11e5-8f25-8151ccb4ba19.png)

If you need any info feel free to ask

**Comment by kumpelblase2** [comment]
Seems to be an issue with not-existent/old settings. Gonna take a look.

**Comment by kumpelblase2** [comment]
Accompanied with a new release as probably multiple people with have this issue. https://github.com/kumpelblase2/proxtop/releases/tag/v0.2.1-alpha3
