### ISSUE TITLE
Automatically save settings upon change

### ISSUE THREAD

**Issue by cuechan** [kumpelblase2/proxtop#76]
when i change some setting (e.g. language to english), leave the settings page and enter it again, all settings are resetted to the default values.

**Comment by kumpelblase2** [comment]
I can't seem to reproduce that, are you sure you clicked on save? I think I should wait to apply language changes until you actually click save, because it gives the idea that settings are saved upon change.

**Comment by cuechan** [comment]
Ok, i dont saw the save button :D.
But also when i dont press `save`, the settings are applied until i click on the setting tab again. In view of usabiltiy this behavior isnt very clear (it looks like its saved but actually isnt).

Maybe its possible to save the settings instantly when any value has been modified?
I would appreciate that.

**Comment by kumpelblase2** [comment]
Apart from the language, none of the settings get applied directly (not sure when or why I did that, should probably git blame myself here).

I'm gonna change it so the language doesn't directly change for the time being, but automatically saving changes might be the way to go.
