### ISSUE TITLE
Avatar is stretched

### ISSUE THREAD

**Issue by cuechan** [kumpelblase2/proxtop#78]
Compared to the [the screenshoots in the repo](https://github.com/kumpelblase2/proxtop/raw/master/screenshots/landing.jpg), my avatar image looks a bit stretched.
![screenshot_2016-03-29_15-48-15](https://cloud.githubusercontent.com/assets/16132887/14124450/da8d3aca-f605-11e5-911f-36ca60353ad6.png)

**Comment by kumpelblase2** [comment]
Ugh this again? Damit, I thought I fixed it <.<
